/** Crop-specific dashboard modules */
export { default as VineDashboard } from './VineDashboard'
export { default as HazelnutDashboard } from './HazelnutDashboard'
export { default as OliveDashboard } from './OliveDashboard'
export { default as WalnutDashboard } from './WalnutDashboard'
export { default as BlueberryDashboard } from './BlueberryDashboard'
export { default as AlmondDashboard } from './AlmondDashboard'
export { default as TeaDashboard } from './TeaDashboard'
export { default as CitrusDashboard } from './CitrusDashboard'
export { default as WheatDashboard } from './WheatDashboard'
export { default as CornDashboard } from './CornDashboard'
export { default as SunflowerDashboard } from './SunflowerDashboard'
export { default as BarleyDashboard } from './BarleyDashboard'
export { default as SoybeanDashboard } from './SoybeanDashboard'
export { default as RapeseedDashboard } from './RapeseedDashboard'
